version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    volumes:
      - ./:/var/www
    depends_on:
      - db
    ports:
      - "9000:9000"
    working_dir: /var/www
    command: sh -c "chmod -R 777 storage bootstrap/cache && php-fpm"

  db:
    image: mariadb:10.6
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: laravel
      MARIADB_USER: user
      MARIADB_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root  # Se mantiene así para compatibilidad con phpMyAdmin

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
    - "80:80"
    volumes:
    - ./:/var/www
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - app

volumes:
  dbdata:
